---
    
- name: set hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"    

- name: copy hosts file
  template: src=templates/{{ hosts_tml }} dest={{ hosts_file }}

- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: apt-get update
  yum:
    update_cache: yes
    
...
